// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCQid1a_wxr8MvjfC4D0-W73v63Ybz6g',
    appId: '1:805791916173:web:a0c668010226f42eb302c4',
    messagingSenderId: '805791916173',
    projectId: 'diaryai-dd8bb',
    authDomain: 'diaryai-dd8bb.firebaseapp.com',
    databaseURL: 'https://diaryai-dd8bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryai-dd8bb.appspot.com',
    measurementId: 'G-YLZEDGV84L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbHTfMZYRmW7kgo-vfJAw_3rQDcPbLpc',
    appId: '1:805791916173:android:58bac90c0bb7921db302c4',
    messagingSenderId: '805791916173',
    projectId: 'diaryai-dd8bb',
    databaseURL: 'https://diaryai-dd8bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryai-dd8bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXn3TljSgk7xBDYHZkNRrxaWnscsbgDQU',
    appId: '1:805791916173:ios:c0142616194b9226b302c4',
    messagingSenderId: '805791916173',
    projectId: 'diaryai-dd8bb',
    databaseURL: 'https://diaryai-dd8bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryai-dd8bb.appspot.com',
    iosClientId: '805791916173-8m8dc811pe5vdp7bdvujb32rsjlib3o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXn3TljSgk7xBDYHZkNRrxaWnscsbgDQU',
    appId: '1:805791916173:ios:c58016ae564d6b19b302c4',
    messagingSenderId: '805791916173',
    projectId: 'diaryai-dd8bb',
    databaseURL: 'https://diaryai-dd8bb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryai-dd8bb.appspot.com',
    iosClientId: '805791916173-28g3cq54q8chr3ec142ucr6001r16hgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryai.RunnerTests',
  );
}
